Traceback (most recent call last):
  File "pami.py", line 954, in <module>
    main(args)
  File "pami.py", line 879, in main
    G = read_load_graph(argsD['orig'][0])
  File "pami.py", line 810, in read_load_graph
    df = Pandas_DataFrame_From_Edgelist([fname])[0]
  File "/Volumes/theory/Grammars/hrg_nets/load_edgelist_from_dataframe.py", line 9, in Pandas_DataFrame_From_Edgelist
    with open(input_graph) as ifile:
IOError: [Errno 2] No such file or directory: './datasets/out.flickrEdges'

dataset: ./datasets/out.flickrEdges
runs: 1, [Errno 2] No such file or directory: './datasets/out.flickrEdges'
